{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1e418570",
   "metadata": {
    "papermill": {
     "duration": 0.004602,
     "end_time": "2023-04-16T19:39:40.721804",
     "exception": false,
     "start_time": "2023-04-16T19:39:40.717202",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# My Thesis Revised\n",
    "-------------------\n",
    "## Uncovering differences between LoL competitions\n",
    "> ### using cluster and discriminant analyses\n",
    "\n",
    "Hello! Welcome to this notebook in which I revise my thesis originally written between April and August of 2021. This was my final dissertation to obtain the degree of Msc. in Statistical Data Analysis. To review the original paper I wrote, including the scientific literature review and written out discussion & conclusion etc., click here [link to thesis PDF]. \n",
    "\n",
    "My thesis analyzed if and how League of Legends competitions around the world differed from one another using a cluster- and discriminant analysis.\n",
    "This notebook acts a purely personal project in which I revise and optimize my original code and foresee a more notebook-like approach, instead of the original R-script. \n",
    "\n",
    "*In case you've got any feedback at all, I'd love to hear from you!*\n",
    "\n",
    "Hope you enjoy!"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb16105d",
   "metadata": {
    "papermill": {
     "duration": 0.002897,
     "end_time": "2023-04-16T19:39:40.727698",
     "exception": false,
     "start_time": "2023-04-16T19:39:40.724801",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# 1. Setting up: Data & Package Loading\n",
    "\n",
    "In this first section I read in the original data (consisting of 4 csv files with similar data)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5c4cd70a",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-04-16T19:39:40.738666Z",
     "iopub.status.busy": "2023-04-16T19:39:40.736249Z",
     "iopub.status.idle": "2023-04-16T19:39:49.058800Z",
     "shell.execute_reply": "2023-04-16T19:39:49.057102Z"
    },
    "papermill": {
     "duration": 8.330375,
     "end_time": "2023-04-16T19:39:49.060964",
     "exception": false,
     "start_time": "2023-04-16T19:39:40.730589",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "'/kaggle/working'"
      ],
      "text/latex": [
       "'/kaggle/working'"
      ],
      "text/markdown": [
       "'/kaggle/working'"
      ],
      "text/plain": [
       "[1] \"/kaggle/working\""
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "── \u001b[1mAttaching core tidyverse packages\u001b[22m ──────────────────────── tidyverse 2.0.0 ──\n",
      "\u001b[32m✔\u001b[39m \u001b[34mdplyr    \u001b[39m 1.1.0     \u001b[32m✔\u001b[39m \u001b[34mreadr    \u001b[39m 2.1.4\n",
      "\u001b[32m✔\u001b[39m \u001b[34mforcats  \u001b[39m 1.0.0     \u001b[32m✔\u001b[39m \u001b[34mstringr  \u001b[39m 1.5.0\n",
      "\u001b[32m✔\u001b[39m \u001b[34mlubridate\u001b[39m 1.9.2     \u001b[32m✔\u001b[39m \u001b[34mtibble   \u001b[39m 3.1.8\n",
      "\u001b[32m✔\u001b[39m \u001b[34mpurrr    \u001b[39m 1.0.1     \u001b[32m✔\u001b[39m \u001b[34mtidyr    \u001b[39m 1.3.0\n",
      "── \u001b[1mConflicts\u001b[22m ────────────────────────────────────────── tidyverse_conflicts() ──\n",
      "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mfilter()\u001b[39m masks \u001b[34mstats\u001b[39m::filter()\n",
      "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mlag()\u001b[39m    masks \u001b[34mstats\u001b[39m::lag()\n",
      "\u001b[36mℹ\u001b[39m Use the conflicted package (\u001b[3m\u001b[34m<http://conflicted.r-lib.org/>\u001b[39m\u001b[23m) to force all conflicts to become errors\n",
      "\n",
      "Attaching package: ‘janitor’\n",
      "\n",
      "\n",
      "The following objects are masked from ‘package:stats’:\n",
      "\n",
      "    chisq.test, fisher.test\n",
      "\n",
      "\n",
      "Loading required package: lattice\n",
      "\n",
      "\n",
      "Attaching package: ‘caret’\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:purrr’:\n",
      "\n",
      "    lift\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:httr’:\n",
      "\n",
      "    progress\n",
      "\n",
      "\n",
      "\n",
      "---------------------\n",
      "Welcome to dendextend version 1.16.0\n",
      "Type citation('dendextend') for how to cite the package.\n",
      "\n",
      "Type browseVignettes(package = 'dendextend') for the package vignette.\n",
      "The github page is: https://github.com/talgalili/dendextend/\n",
      "\n",
      "Suggestions and bug-reports can be submitted at: https://github.com/talgalili/dendextend/issues\n",
      "You may ask questions at stackoverflow, use the r and dendextend tags: \n",
      "\t https://stackoverflow.com/questions/tagged/dendextend\n",
      "\n",
      "\tTo suppress this message use:  suppressPackageStartupMessages(library(dendextend))\n",
      "---------------------\n",
      "\n",
      "\n",
      "\n",
      "Attaching package: ‘dendextend’\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:stats’:\n",
      "\n",
      "    cutree\n",
      "\n",
      "\n",
      "Registered S3 methods overwritten by 'fmsb':\n",
      "  method    from\n",
      "  print.roc pROC\n",
      "  plot.roc  pROC\n",
      "\n",
      "\n",
      "Attaching package: ‘descr’\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:janitor’:\n",
      "\n",
      "    crosstab\n",
      "\n",
      "\n",
      "\n",
      "Attaching package: ‘MASS’\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:dplyr’:\n",
      "\n",
      "    select\n",
      "\n",
      "\n",
      "Loading required package: class\n",
      "\n",
      "Loaded mda 0.5-3\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<ol>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'fmsb'</li><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'descr'</li><li>'fmsb'</li><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'xtable'</li><li>'descr'</li><li>'fmsb'</li><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'MASS'</li><li>'xtable'</li><li>'descr'</li><li>'fmsb'</li><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "\t<li><style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>'mda'</li><li>'class'</li><li>'MASS'</li><li>'xtable'</li><li>'descr'</li><li>'fmsb'</li><li>'NbClust'</li><li>'dendextend'</li><li>'caret'</li><li>'lattice'</li><li>'janitor'</li><li>'lubridate'</li><li>'forcats'</li><li>'stringr'</li><li>'dplyr'</li><li>'purrr'</li><li>'readr'</li><li>'tidyr'</li><li>'tibble'</li><li>'tidyverse'</li><li>'ggplot2'</li><li>'stats'</li><li>'graphics'</li><li>'grDevices'</li><li>'utils'</li><li>'datasets'</li><li>'bigrquery'</li><li>'httr'</li><li>'methods'</li><li>'base'</li></ol>\n",
       "</li>\n",
       "</ol>\n"
      ],
      "text/latex": [
       "\\begin{enumerate}\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'fmsb'\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'descr'\n",
       "\\item 'fmsb'\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'xtable'\n",
       "\\item 'descr'\n",
       "\\item 'fmsb'\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'MASS'\n",
       "\\item 'xtable'\n",
       "\\item 'descr'\n",
       "\\item 'fmsb'\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\item \\begin{enumerate*}\n",
       "\\item 'mda'\n",
       "\\item 'class'\n",
       "\\item 'MASS'\n",
       "\\item 'xtable'\n",
       "\\item 'descr'\n",
       "\\item 'fmsb'\n",
       "\\item 'NbClust'\n",
       "\\item 'dendextend'\n",
       "\\item 'caret'\n",
       "\\item 'lattice'\n",
       "\\item 'janitor'\n",
       "\\item 'lubridate'\n",
       "\\item 'forcats'\n",
       "\\item 'stringr'\n",
       "\\item 'dplyr'\n",
       "\\item 'purrr'\n",
       "\\item 'readr'\n",
       "\\item 'tidyr'\n",
       "\\item 'tibble'\n",
       "\\item 'tidyverse'\n",
       "\\item 'ggplot2'\n",
       "\\item 'stats'\n",
       "\\item 'graphics'\n",
       "\\item 'grDevices'\n",
       "\\item 'utils'\n",
       "\\item 'datasets'\n",
       "\\item 'bigrquery'\n",
       "\\item 'httr'\n",
       "\\item 'methods'\n",
       "\\item 'base'\n",
       "\\end{enumerate*}\n",
       "\n",
       "\\end{enumerate}\n"
      ],
      "text/markdown": [
       "1. 1. 'ggplot2'\n",
       "2. 'stats'\n",
       "3. 'graphics'\n",
       "4. 'grDevices'\n",
       "5. 'utils'\n",
       "6. 'datasets'\n",
       "7. 'bigrquery'\n",
       "8. 'httr'\n",
       "9. 'methods'\n",
       "10. 'base'\n",
       "\n",
       "\n",
       "\n",
       "2. 1. 'lubridate'\n",
       "2. 'forcats'\n",
       "3. 'stringr'\n",
       "4. 'dplyr'\n",
       "5. 'purrr'\n",
       "6. 'readr'\n",
       "7. 'tidyr'\n",
       "8. 'tibble'\n",
       "9. 'tidyverse'\n",
       "10. 'ggplot2'\n",
       "11. 'stats'\n",
       "12. 'graphics'\n",
       "13. 'grDevices'\n",
       "14. 'utils'\n",
       "15. 'datasets'\n",
       "16. 'bigrquery'\n",
       "17. 'httr'\n",
       "18. 'methods'\n",
       "19. 'base'\n",
       "\n",
       "\n",
       "\n",
       "3. 1. 'janitor'\n",
       "2. 'lubridate'\n",
       "3. 'forcats'\n",
       "4. 'stringr'\n",
       "5. 'dplyr'\n",
       "6. 'purrr'\n",
       "7. 'readr'\n",
       "8. 'tidyr'\n",
       "9. 'tibble'\n",
       "10. 'tidyverse'\n",
       "11. 'ggplot2'\n",
       "12. 'stats'\n",
       "13. 'graphics'\n",
       "14. 'grDevices'\n",
       "15. 'utils'\n",
       "16. 'datasets'\n",
       "17. 'bigrquery'\n",
       "18. 'httr'\n",
       "19. 'methods'\n",
       "20. 'base'\n",
       "\n",
       "\n",
       "\n",
       "4. 1. 'caret'\n",
       "2. 'lattice'\n",
       "3. 'janitor'\n",
       "4. 'lubridate'\n",
       "5. 'forcats'\n",
       "6. 'stringr'\n",
       "7. 'dplyr'\n",
       "8. 'purrr'\n",
       "9. 'readr'\n",
       "10. 'tidyr'\n",
       "11. 'tibble'\n",
       "12. 'tidyverse'\n",
       "13. 'ggplot2'\n",
       "14. 'stats'\n",
       "15. 'graphics'\n",
       "16. 'grDevices'\n",
       "17. 'utils'\n",
       "18. 'datasets'\n",
       "19. 'bigrquery'\n",
       "20. 'httr'\n",
       "21. 'methods'\n",
       "22. 'base'\n",
       "\n",
       "\n",
       "\n",
       "5. 1. 'dendextend'\n",
       "2. 'caret'\n",
       "3. 'lattice'\n",
       "4. 'janitor'\n",
       "5. 'lubridate'\n",
       "6. 'forcats'\n",
       "7. 'stringr'\n",
       "8. 'dplyr'\n",
       "9. 'purrr'\n",
       "10. 'readr'\n",
       "11. 'tidyr'\n",
       "12. 'tibble'\n",
       "13. 'tidyverse'\n",
       "14. 'ggplot2'\n",
       "15. 'stats'\n",
       "16. 'graphics'\n",
       "17. 'grDevices'\n",
       "18. 'utils'\n",
       "19. 'datasets'\n",
       "20. 'bigrquery'\n",
       "21. 'httr'\n",
       "22. 'methods'\n",
       "23. 'base'\n",
       "\n",
       "\n",
       "\n",
       "6. 1. 'NbClust'\n",
       "2. 'dendextend'\n",
       "3. 'caret'\n",
       "4. 'lattice'\n",
       "5. 'janitor'\n",
       "6. 'lubridate'\n",
       "7. 'forcats'\n",
       "8. 'stringr'\n",
       "9. 'dplyr'\n",
       "10. 'purrr'\n",
       "11. 'readr'\n",
       "12. 'tidyr'\n",
       "13. 'tibble'\n",
       "14. 'tidyverse'\n",
       "15. 'ggplot2'\n",
       "16. 'stats'\n",
       "17. 'graphics'\n",
       "18. 'grDevices'\n",
       "19. 'utils'\n",
       "20. 'datasets'\n",
       "21. 'bigrquery'\n",
       "22. 'httr'\n",
       "23. 'methods'\n",
       "24. 'base'\n",
       "\n",
       "\n",
       "\n",
       "7. 1. 'fmsb'\n",
       "2. 'NbClust'\n",
       "3. 'dendextend'\n",
       "4. 'caret'\n",
       "5. 'lattice'\n",
       "6. 'janitor'\n",
       "7. 'lubridate'\n",
       "8. 'forcats'\n",
       "9. 'stringr'\n",
       "10. 'dplyr'\n",
       "11. 'purrr'\n",
       "12. 'readr'\n",
       "13. 'tidyr'\n",
       "14. 'tibble'\n",
       "15. 'tidyverse'\n",
       "16. 'ggplot2'\n",
       "17. 'stats'\n",
       "18. 'graphics'\n",
       "19. 'grDevices'\n",
       "20. 'utils'\n",
       "21. 'datasets'\n",
       "22. 'bigrquery'\n",
       "23. 'httr'\n",
       "24. 'methods'\n",
       "25. 'base'\n",
       "\n",
       "\n",
       "\n",
       "8. 1. 'descr'\n",
       "2. 'fmsb'\n",
       "3. 'NbClust'\n",
       "4. 'dendextend'\n",
       "5. 'caret'\n",
       "6. 'lattice'\n",
       "7. 'janitor'\n",
       "8. 'lubridate'\n",
       "9. 'forcats'\n",
       "10. 'stringr'\n",
       "11. 'dplyr'\n",
       "12. 'purrr'\n",
       "13. 'readr'\n",
       "14. 'tidyr'\n",
       "15. 'tibble'\n",
       "16. 'tidyverse'\n",
       "17. 'ggplot2'\n",
       "18. 'stats'\n",
       "19. 'graphics'\n",
       "20. 'grDevices'\n",
       "21. 'utils'\n",
       "22. 'datasets'\n",
       "23. 'bigrquery'\n",
       "24. 'httr'\n",
       "25. 'methods'\n",
       "26. 'base'\n",
       "\n",
       "\n",
       "\n",
       "9. 1. 'xtable'\n",
       "2. 'descr'\n",
       "3. 'fmsb'\n",
       "4. 'NbClust'\n",
       "5. 'dendextend'\n",
       "6. 'caret'\n",
       "7. 'lattice'\n",
       "8. 'janitor'\n",
       "9. 'lubridate'\n",
       "10. 'forcats'\n",
       "11. 'stringr'\n",
       "12. 'dplyr'\n",
       "13. 'purrr'\n",
       "14. 'readr'\n",
       "15. 'tidyr'\n",
       "16. 'tibble'\n",
       "17. 'tidyverse'\n",
       "18. 'ggplot2'\n",
       "19. 'stats'\n",
       "20. 'graphics'\n",
       "21. 'grDevices'\n",
       "22. 'utils'\n",
       "23. 'datasets'\n",
       "24. 'bigrquery'\n",
       "25. 'httr'\n",
       "26. 'methods'\n",
       "27. 'base'\n",
       "\n",
       "\n",
       "\n",
       "10. 1. 'MASS'\n",
       "2. 'xtable'\n",
       "3. 'descr'\n",
       "4. 'fmsb'\n",
       "5. 'NbClust'\n",
       "6. 'dendextend'\n",
       "7. 'caret'\n",
       "8. 'lattice'\n",
       "9. 'janitor'\n",
       "10. 'lubridate'\n",
       "11. 'forcats'\n",
       "12. 'stringr'\n",
       "13. 'dplyr'\n",
       "14. 'purrr'\n",
       "15. 'readr'\n",
       "16. 'tidyr'\n",
       "17. 'tibble'\n",
       "18. 'tidyverse'\n",
       "19. 'ggplot2'\n",
       "20. 'stats'\n",
       "21. 'graphics'\n",
       "22. 'grDevices'\n",
       "23. 'utils'\n",
       "24. 'datasets'\n",
       "25. 'bigrquery'\n",
       "26. 'httr'\n",
       "27. 'methods'\n",
       "28. 'base'\n",
       "\n",
       "\n",
       "\n",
       "11. 1. 'mda'\n",
       "2. 'class'\n",
       "3. 'MASS'\n",
       "4. 'xtable'\n",
       "5. 'descr'\n",
       "6. 'fmsb'\n",
       "7. 'NbClust'\n",
       "8. 'dendextend'\n",
       "9. 'caret'\n",
       "10. 'lattice'\n",
       "11. 'janitor'\n",
       "12. 'lubridate'\n",
       "13. 'forcats'\n",
       "14. 'stringr'\n",
       "15. 'dplyr'\n",
       "16. 'purrr'\n",
       "17. 'readr'\n",
       "18. 'tidyr'\n",
       "19. 'tibble'\n",
       "20. 'tidyverse'\n",
       "21. 'ggplot2'\n",
       "22. 'stats'\n",
       "23. 'graphics'\n",
       "24. 'grDevices'\n",
       "25. 'utils'\n",
       "26. 'datasets'\n",
       "27. 'bigrquery'\n",
       "28. 'httr'\n",
       "29. 'methods'\n",
       "30. 'base'\n",
       "\n",
       "\n",
       "\n",
       "\n",
       "\n"
      ],
      "text/plain": [
       "[[1]]\n",
       " [1] \"ggplot2\"   \"stats\"     \"graphics\"  \"grDevices\" \"utils\"     \"datasets\" \n",
       " [7] \"bigrquery\" \"httr\"      \"methods\"   \"base\"     \n",
       "\n",
       "[[2]]\n",
       " [1] \"lubridate\" \"forcats\"   \"stringr\"   \"dplyr\"     \"purrr\"     \"readr\"    \n",
       " [7] \"tidyr\"     \"tibble\"    \"tidyverse\" \"ggplot2\"   \"stats\"     \"graphics\" \n",
       "[13] \"grDevices\" \"utils\"     \"datasets\"  \"bigrquery\" \"httr\"      \"methods\"  \n",
       "[19] \"base\"     \n",
       "\n",
       "[[3]]\n",
       " [1] \"janitor\"   \"lubridate\" \"forcats\"   \"stringr\"   \"dplyr\"     \"purrr\"    \n",
       " [7] \"readr\"     \"tidyr\"     \"tibble\"    \"tidyverse\" \"ggplot2\"   \"stats\"    \n",
       "[13] \"graphics\"  \"grDevices\" \"utils\"     \"datasets\"  \"bigrquery\" \"httr\"     \n",
       "[19] \"methods\"   \"base\"     \n",
       "\n",
       "[[4]]\n",
       " [1] \"caret\"     \"lattice\"   \"janitor\"   \"lubridate\" \"forcats\"   \"stringr\"  \n",
       " [7] \"dplyr\"     \"purrr\"     \"readr\"     \"tidyr\"     \"tibble\"    \"tidyverse\"\n",
       "[13] \"ggplot2\"   \"stats\"     \"graphics\"  \"grDevices\" \"utils\"     \"datasets\" \n",
       "[19] \"bigrquery\" \"httr\"      \"methods\"   \"base\"     \n",
       "\n",
       "[[5]]\n",
       " [1] \"dendextend\" \"caret\"      \"lattice\"    \"janitor\"    \"lubridate\" \n",
       " [6] \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"     \n",
       "[11] \"tidyr\"      \"tibble\"     \"tidyverse\"  \"ggplot2\"    \"stats\"     \n",
       "[16] \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"   \"bigrquery\" \n",
       "[21] \"httr\"       \"methods\"    \"base\"      \n",
       "\n",
       "[[6]]\n",
       " [1] \"NbClust\"    \"dendextend\" \"caret\"      \"lattice\"    \"janitor\"   \n",
       " [6] \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"     \n",
       "[11] \"readr\"      \"tidyr\"      \"tibble\"     \"tidyverse\"  \"ggplot2\"   \n",
       "[16] \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"  \n",
       "[21] \"bigrquery\"  \"httr\"       \"methods\"    \"base\"      \n",
       "\n",
       "[[7]]\n",
       " [1] \"fmsb\"       \"NbClust\"    \"dendextend\" \"caret\"      \"lattice\"   \n",
       " [6] \"janitor\"    \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"     \n",
       "[11] \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"     \"tidyverse\" \n",
       "[16] \"ggplot2\"    \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"     \n",
       "[21] \"datasets\"   \"bigrquery\"  \"httr\"       \"methods\"    \"base\"      \n",
       "\n",
       "[[8]]\n",
       " [1] \"descr\"      \"fmsb\"       \"NbClust\"    \"dendextend\" \"caret\"     \n",
       " [6] \"lattice\"    \"janitor\"    \"lubridate\"  \"forcats\"    \"stringr\"   \n",
       "[11] \"dplyr\"      \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"    \n",
       "[16] \"tidyverse\"  \"ggplot2\"    \"stats\"      \"graphics\"   \"grDevices\" \n",
       "[21] \"utils\"      \"datasets\"   \"bigrquery\"  \"httr\"       \"methods\"   \n",
       "[26] \"base\"      \n",
       "\n",
       "[[9]]\n",
       " [1] \"xtable\"     \"descr\"      \"fmsb\"       \"NbClust\"    \"dendextend\"\n",
       " [6] \"caret\"      \"lattice\"    \"janitor\"    \"lubridate\"  \"forcats\"   \n",
       "[11] \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"      \"tidyr\"     \n",
       "[16] \"tibble\"     \"tidyverse\"  \"ggplot2\"    \"stats\"      \"graphics\"  \n",
       "[21] \"grDevices\"  \"utils\"      \"datasets\"   \"bigrquery\"  \"httr\"      \n",
       "[26] \"methods\"    \"base\"      \n",
       "\n",
       "[[10]]\n",
       " [1] \"MASS\"       \"xtable\"     \"descr\"      \"fmsb\"       \"NbClust\"   \n",
       " [6] \"dendextend\" \"caret\"      \"lattice\"    \"janitor\"    \"lubridate\" \n",
       "[11] \"forcats\"    \"stringr\"    \"dplyr\"      \"purrr\"      \"readr\"     \n",
       "[16] \"tidyr\"      \"tibble\"     \"tidyverse\"  \"ggplot2\"    \"stats\"     \n",
       "[21] \"graphics\"   \"grDevices\"  \"utils\"      \"datasets\"   \"bigrquery\" \n",
       "[26] \"httr\"       \"methods\"    \"base\"      \n",
       "\n",
       "[[11]]\n",
       " [1] \"mda\"        \"class\"      \"MASS\"       \"xtable\"     \"descr\"     \n",
       " [6] \"fmsb\"       \"NbClust\"    \"dendextend\" \"caret\"      \"lattice\"   \n",
       "[11] \"janitor\"    \"lubridate\"  \"forcats\"    \"stringr\"    \"dplyr\"     \n",
       "[16] \"purrr\"      \"readr\"      \"tidyr\"      \"tibble\"     \"tidyverse\" \n",
       "[21] \"ggplot2\"    \"stats\"      \"graphics\"   \"grDevices\"  \"utils\"     \n",
       "[26] \"datasets\"   \"bigrquery\"  \"httr\"       \"methods\"    \"base\"      \n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[1m\u001b[22mNew names:\n",
      "\u001b[36m•\u001b[39m `` -> `...1`\n",
      "\u001b[1mRows: \u001b[22m\u001b[34m1982\u001b[39m \u001b[1mColumns: \u001b[22m\u001b[34m64\u001b[39m\n",
      "\u001b[36m──\u001b[39m \u001b[1mColumn specification\u001b[22m \u001b[36m────────────────────────────────────────────────────────\u001b[39m\n",
      "\u001b[1mDelimiter:\u001b[22m \",\"\n",
      "\u001b[31mchr\u001b[39m  (1): league\n",
      "\u001b[32mdbl\u001b[39m (63): ...1, gamelength, assists, teamkills, teamdeaths, team_kpm, ckpm, ...\n",
      "\n",
      "\u001b[36mℹ\u001b[39m Use `spec()` to retrieve the full column specification for this data.\n",
      "\u001b[36mℹ\u001b[39m Specify the column types or set `show_col_types = FALSE` to quiet this message.\n",
      "\u001b[1m\u001b[22mNew names:\n",
      "\u001b[36m•\u001b[39m `` -> `...1`\n",
      "\u001b[1mRows: \u001b[22m\u001b[34m1544\u001b[39m \u001b[1mColumns: \u001b[22m\u001b[34m64\u001b[39m\n",
      "\u001b[36m──\u001b[39m \u001b[1mColumn specification\u001b[22m \u001b[36m────────────────────────────────────────────────────────\u001b[39m\n",
      "\u001b[1mDelimiter:\u001b[22m \",\"\n",
      "\u001b[31mchr\u001b[39m  (1): league\n",
      "\u001b[32mdbl\u001b[39m (63): ...1, gamelength, assists, teamkills, teamdeaths, team_kpm, ckpm, ...\n",
      "\n",
      "\u001b[36mℹ\u001b[39m Use `spec()` to retrieve the full column specification for this data.\n",
      "\u001b[36mℹ\u001b[39m Specify the column types or set `show_col_types = FALSE` to quiet this message.\n",
      "\u001b[1m\u001b[22mNew names:\n",
      "\u001b[36m•\u001b[39m `` -> `...1`\n",
      "\u001b[1mRows: \u001b[22m\u001b[34m1508\u001b[39m \u001b[1mColumns: \u001b[22m\u001b[34m64\u001b[39m\n",
      "\u001b[36m──\u001b[39m \u001b[1mColumn specification\u001b[22m \u001b[36m────────────────────────────────────────────────────────\u001b[39m\n",
      "\u001b[1mDelimiter:\u001b[22m \",\"\n",
      "\u001b[31mchr\u001b[39m  (1): league\n",
      "\u001b[32mdbl\u001b[39m (63): ...1, gamelength, assists, teamkills, teamdeaths, team_kpm, ckpm, ...\n",
      "\n",
      "\u001b[36mℹ\u001b[39m Use `spec()` to retrieve the full column specification for this data.\n",
      "\u001b[36mℹ\u001b[39m Specify the column types or set `show_col_types = FALSE` to quiet this message.\n",
      "\u001b[1m\u001b[22mNew names:\n",
      "\u001b[36m•\u001b[39m `` -> `...1`\n",
      "\u001b[1mRows: \u001b[22m\u001b[34m1364\u001b[39m \u001b[1mColumns: \u001b[22m\u001b[34m64\u001b[39m\n",
      "\u001b[36m──\u001b[39m \u001b[1mColumn specification\u001b[22m \u001b[36m────────────────────────────────────────────────────────\u001b[39m\n",
      "\u001b[1mDelimiter:\u001b[22m \",\"\n",
      "\u001b[31mchr\u001b[39m  (1): league\n",
      "\u001b[32mdbl\u001b[39m (63): ...1, gamelength, assists, teamkills, teamdeaths, team_kpm, ckpm, ...\n",
      "\n",
      "\u001b[36mℹ\u001b[39m Use `spec()` to retrieve the full column specification for this data.\n",
      "\u001b[36mℹ\u001b[39m Specify the column types or set `show_col_types = FALSE` to quiet this message.\n"
     ]
    }
   ],
   "source": [
    "                ######################\n",
    "                ### Thesis R file  ###\n",
    "                ##  Jappe Bulckaen  ##\n",
    "                ######################\n",
    "\n",
    "#### Data & Package loading ####\n",
    "                \n",
    "set.seed(0)\n",
    "getwd()\n",
    "\n",
    "\n",
    "# https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them\n",
    "# List of needed packages:\n",
    "list_of_packages = c(\"ggplot2\", \"tidyverse\", \"janitor\", #\"factoextra\",  \n",
    "                     \"caret\",\"dendextend\",\"NbClust\", \"fmsb\",\"descr\",  \"xtable\",\n",
    "                     'MASS', \"mda\" #, \"ggpubr\"\n",
    "                     )\n",
    "\n",
    "# Check what packages are still needed (i.e. not already installed)\n",
    "needed_packages = list_of_packages[!(list_of_packages %in% installed.packages()[, \"Package\"])]\n",
    "\n",
    "# If the \"needed_packages\" variable is empty, the missing packages are installed\n",
    "if(length(needed_packages)) install.packages(needed_packages)\n",
    "\n",
    "# Load libraries\n",
    "# https://gist.github.com/RobertMyles/96665be044540e9ac668ee697dac6db7\n",
    "lapply(list_of_packages, library, character.only = TRUE)\n",
    "\n",
    "# Original Data Loading, which loades ALL data (appr. 200+MB)\n",
    "# data_17 <- read_csv(\"Data/2017_LoL_esports_match_data_from_OraclesElixir_20210401.csv\")\n",
    "# data_18 <- read_csv(\"Data/2018_LoL_esports_match_data_from_OraclesElixir_20210401.csv\")\n",
    "# data_19 <- read_csv(\"Data/2019_LoL_esports_match_data_from_OraclesElixir_20210401.csv\")\n",
    "# data_20 <- read_csv(\"Data/2020_LoL_esports_match_data_from_OraclesElixir_20210401.csv\")\n",
    "\n",
    "\n",
    "data_17 <- read_csv(\"/kaggle/input/lol-pro-teams-data-2017-2020/LoLTeamData_2017.csv\")\n",
    "data_18 <- read_csv(\"/kaggle/input/lol-pro-teams-data-2017-2020/LoLTeamData_2018.csv\")\n",
    "data_19 <- read_csv(\"/kaggle/input/lol-pro-teams-data-2017-2020/LoLTeamData_2019.csv\")\n",
    "data_20 <- read_csv(\"/kaggle/input/lol-pro-teams-data-2017-2020/LoLTeamData_2020.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "161a1a9a",
   "metadata": {
    "papermill": {
     "duration": 0.006093,
     "end_time": "2023-04-16T19:39:49.073880",
     "exception": false,
     "start_time": "2023-04-16T19:39:49.067787",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "## Data Exploration and Cleaning:\n",
    "\n",
    "In this section I've written a cleaning function to keep the needed data: \n",
    "- I've kept only the regions that made it to the group stage of the respective World Championships that year\n",
    "- I've deleted the player-related columns (since we only analyse the team as a whole)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4add6fa1",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-04-16T19:39:49.117441Z",
     "iopub.status.busy": "2023-04-16T19:39:49.087996Z",
     "iopub.status.idle": "2023-04-16T19:39:49.646259Z",
     "shell.execute_reply": "2023-04-16T19:39:49.644531Z"
    },
    "papermill": {
     "duration": 0.568779,
     "end_time": "2023-04-16T19:39:49.648586",
     "exception": false,
     "start_time": "2023-04-16T19:39:49.079807",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>1982</li><li>64</li></ol>\n"
      ],
      "text/latex": [
       "\\begin{enumerate*}\n",
       "\\item 1982\n",
       "\\item 64\n",
       "\\end{enumerate*}\n"
      ],
      "text/markdown": [
       "1. 1982\n",
       "2. 64\n",
       "\n",
       "\n"
      ],
      "text/plain": [
       "[1] 1982   64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>1544</li><li>64</li></ol>\n"
      ],
      "text/latex": [
       "\\begin{enumerate*}\n",
       "\\item 1544\n",
       "\\item 64\n",
       "\\end{enumerate*}\n"
      ],
      "text/markdown": [
       "1. 1544\n",
       "2. 64\n",
       "\n",
       "\n"
      ],
      "text/plain": [
       "[1] 1544   64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>1508</li><li>64</li></ol>\n"
      ],
      "text/latex": [
       "\\begin{enumerate*}\n",
       "\\item 1508\n",
       "\\item 64\n",
       "\\end{enumerate*}\n"
      ],
      "text/markdown": [
       "1. 1508\n",
       "2. 64\n",
       "\n",
       "\n"
      ],
      "text/plain": [
       "[1] 1508   64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".list-inline {list-style: none; margin:0; padding: 0}\n",
       ".list-inline>li {display: inline-block}\n",
       ".list-inline>li:not(:last-child)::after {content: \"\\00b7\"; padding: 0 .5ex}\n",
       "</style>\n",
       "<ol class=list-inline><li>1364</li><li>64</li></ol>\n"
      ],
      "text/latex": [
       "\\begin{enumerate*}\n",
       "\\item 1364\n",
       "\\item 64\n",
       "\\end{enumerate*}\n"
      ],
      "text/markdown": [
       "1. 1364\n",
       "2. 64\n",
       "\n",
       "\n"
      ],
      "text/plain": [
       "[1] 1364   64"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# input = df + year (name changes of leagues)\n",
    "filter_lol_df <- function(dataset, LoL_year) {\n",
    "  \n",
    "  if(!is.numeric(LoL_year)){\n",
    "    stop(\"Input year incorrect\") \n",
    "  }\n",
    "  \n",
    "  # study only regions that participated at the \n",
    "  # World Championship Group stage per year:\n",
    "  if(LoL_year==2017) {\n",
    "    regions_keep <- c(\"LCK\",\"GPL\",\"TCL\",\"EU LCS\",\"NA LCS\",\"LMS\")\n",
    "  } else if(LoL_year == 2018) {\n",
    "    regions_keep <- c(\"LCK\",\"VCS\",\"EU LCS\",\"NA LCS\",\"LMS\")\n",
    "  } else if(LoL_year == 2019) {\n",
    "    regions_keep <- c(\"LCK\",\"VCS\",\"LEC\",\"LCS\",\"LMS\")\n",
    "  } else if(LoL_year == 2020) {\n",
    "    regions_keep <- c(\"LCK\",\"LCL\",\"LEC\",\"LCS\",\"PCS\")\n",
    "  }\n",
    "  \n",
    "  # Delete all non-informative/string columns + binary/categorical columns\n",
    "  cols_del <- c(\"gameid\",\"team\", \"datacompleteness\", \"date\", \"year\", \"url\", \n",
    "                \"playoffs\", \"split\", \"player\", \"champion\", \"firstbloodkill\", \n",
    "                \"game\", \"playerid\", \"side\",  \"firstbloodvictim\", \"patch\",  \n",
    "                \"firstbloodassist\", \"ban1\", \"ban2\", \"ban3\", \"ban4\", \"ban5\", \n",
    "                \"kills\", \"deaths\", \"firstdragon\", \"firstblood\", \"firstherald\", \n",
    "                \"elementaldrakes\", \"opp_elementaldrakes\", \"infernals\",\"game\",\n",
    "                \"mountains\", \"oceans\", \"clouds\",\"dragons (type unknown)\", \n",
    "                \"elders\", \"opp_elders\", \"firstbaron\", \"firsttower\", \"heralds\",\n",
    "                \"firstmidtower\", \"firsttothreetowers\", \"result\", \"position\", \n",
    "                \"total cs\", \"damageshare\", \"damagemitigatedperminute\", \n",
    "                \"visionscore\", \"vspm\", \"earnedgoldshare\",  \"opp_heralds\", \n",
    "                \"doublekills\",\"triplekills\", \"quadrakills\",\"pentakills\")\n",
    "  # output = filtered df\n",
    "  dataset <- dataset %>% \n",
    "    # Filter on the studied regions\n",
    "    filter(league %in% regions_keep, \n",
    "           position == \"team\",            # Only keep 'team' rows, delete all player rows\n",
    "           result == 1,                   # Keep wins only to avoid mirrored entries\n",
    "           year == LoL_year) %>%          # Delete promotion games \n",
    "    dplyr::select(!all_of(cols_del)) %>%  # delete columns defined earlier\n",
    "    mutate(league = as.factor(league)) %>%\n",
    "    drop_na() %>%                         # drop all NA rows\n",
    "    clean_names()%>%                      # replaces all spaces in names with \"_\"\n",
    "    mutate_at(vars(-league), list(scale)) # scale the variables (order of magnitudes differ)\n",
    "}\n",
    "\n",
    "# data_17 <- filter_lol_df(data_17, 2017)\n",
    "# data_18 <- filter_lol_df(data_18, 2018)\n",
    "# data_19 <- filter_lol_df(data_19, 2019)\n",
    "# data_20 <- filter_lol_df(data_20, 2020)\n",
    "\n",
    "dim(data_17)\n",
    "dim(data_18)\n",
    "dim(data_19)\n",
    "dim(data_20)\n",
    "\n",
    "matr_17 <- as.matrix(data_17[c(-1)])\n",
    "matr_18 <- as.matrix(data_18[c(-1)])\n",
    "matr_19 <- as.matrix(data_19[c(-1)])\n",
    "matr_20 <- as.matrix(data_20[c(-1)])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3500b832",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-04-16T19:15:53.846681Z",
     "iopub.status.busy": "2023-04-16T19:15:53.845065Z",
     "iopub.status.idle": "2023-04-16T19:16:04.665301Z"
    },
    "papermill": {
     "duration": 0.006721,
     "end_time": "2023-04-16T19:39:49.662198",
     "exception": false,
     "start_time": "2023-04-16T19:39:49.655477",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "#### PCA DO RUN  ####\n",
    "## DO RUN:\n",
    "# fit PCA for each year:\n",
    "pca_fit_2017 <- data_17 %>% \n",
    "  dplyr::select(where(is.numeric)) %>% # retain only numeric columns        \n",
    "  prcomp()                             # perform PCA\n",
    "\n",
    "pca_fit_2018 <- data_18 %>% \n",
    "  dplyr::select(where(is.numeric)) %>% # retain only numeric columns                      \n",
    "  prcomp()\n",
    "\n",
    "pca_fit_2019 <- data_19 %>% \n",
    "  dplyr::select(where(is.numeric)) %>% # retain only numeric columns\n",
    "  prcomp()\n",
    "\n",
    "pca_fit_2020 <- data_20 %>% \n",
    "  dplyr::select(where(is.numeric)) %>% # retain only numeric columns\n",
    "  prcomp()\n",
    "\n",
    "# Set up reduced datasets:\n",
    "reduced_17 <- pca_fit_2017$x[,1:8] %>%\n",
    "  as.data.frame() %>%\n",
    "  mutate(leagues = data_17$league)\n",
    "\n",
    "reduced_18 <- pca_fit_2018$x[,1:8] %>%\n",
    "  as.data.frame() %>%\n",
    "  mutate(leagues = data_18$league)\n",
    "\n",
    "reduced_19 <- pca_fit_2019$x[,1:8] %>%\n",
    "  as.data.frame() %>%\n",
    "  mutate(leagues = data_19$league)\n",
    "\n",
    "reduced_20 <- pca_fit_2020$x[,1:8] %>%\n",
    "  as.data.frame() %>%\n",
    "  mutate(leagues = data_20$league)\n",
    "\n",
    "#### PCA rest ####\n",
    "\n",
    "\n",
    "# 2017\n",
    "summary(pca_fit_2017)\n",
    "scree_pca_17 <- fviz_eig(pca_fit_2017, addlabels = T, \n",
    "                         ncp=10, main=\"2017\", hjust = 0.5) \n",
    "\n",
    "scree_pca_17\n",
    "fviz_pca_var(pca_fit_2017, repel=T)                               # check contribution \n",
    "fviz_pca_var(pca_fit_2017, repel=T, axes = c(3,4))                # of features per 2 PC's  \n",
    "fviz_pca_var(pca_fit_2017, repel=T, axes = c(5,6))\n",
    "fviz_pca_var(pca_fit_2017, repel=T, axes = c(7,8))\n",
    "fviz_pca_ind(pca_fit_2017, \n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_17$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2017, \n",
    "             axes=c(3, 4),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_17$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2017, \n",
    "             axes=c(5,6),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_17$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2017, \n",
    "             axes=c(7, 8),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_17$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=1, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=2, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=3, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=4, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=5, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=6, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=7, top=10)\n",
    "fviz_contrib(pca_fit_2017, choice = \"var\", axes=8, top=10)\n",
    "\n",
    "# 2018\n",
    "summary(pca_fit_2018)\n",
    "scree_pca_18 <- fviz_eig(pca_fit_2018, addlabels = T, \n",
    "                         npc=10, main=\"2018\", hjust = 0.5)\n",
    "\n",
    "\n",
    "fviz_pca_var(pca_fit_2018, repel=T)\n",
    "fviz_pca_var(pca_fit_2018, repel=T, axes = c(3,4))\n",
    "fviz_pca_var(pca_fit_2018, repel=T, axes = c(5,6))\n",
    "fviz_pca_var(pca_fit_2018, repel=T, axes = c(7,8))\n",
    "fviz_pca_ind(pca_fit_2018, \n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_18$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2018, \n",
    "             axes=c(3, 4),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_18$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=1, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=2, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=3, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=4, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=5, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=6, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=7, top=10)\n",
    "fviz_contrib(pca_fit_2018, choice = \"var\", axes=8, top=10)\n",
    "\n",
    "# 2019\n",
    "summary(pca_fit_2019)\n",
    "scree_pca_19 <- fviz_eig(pca_fit_2019, addlabels = T, \n",
    "                         ncp=10, main=\"2019\", hjust = 0.5) # scree plot\n",
    "\n",
    "fviz_pca_var(pca_fit_2019, repel=T)           # loadings of first 2 pc's\n",
    "fviz_pca_var(pca_fit_2019, repel=T, axes = c(3,4))\n",
    "fviz_pca_var(pca_fit_2019, repel=T, axes = c(5,6))\n",
    "fviz_pca_var(pca_fit_2019, repel=T, axes = c(7,8))\n",
    "fviz_pca_ind(pca_fit_2019, \n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_19$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2019, \n",
    "             axes=c(3,4),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_19$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=1, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=2, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=3, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=4, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=5, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=6, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=7, top=10)\n",
    "fviz_contrib(pca_fit_2019, choice = \"var\", axes=8, top=10)\n",
    "\n",
    "# 2020\n",
    "summary(pca_fit_2020)\n",
    "scree_pca_20 <- fviz_eig(pca_fit_2020, addlabels = T, \n",
    "                         ncp=10, main=\"2020\", hjust = 0.5)\n",
    "fviz_pca_var(pca_fit_2020, repel=T)\n",
    "fviz_pca_var(pca_fit_2020, repel=T, axes = c(3,4))\n",
    "fviz_pca_var(pca_fit_2020, repel=T, axes = c(5,6))\n",
    "fviz_pca_var(pca_fit_2020, repel=T, axes = c(7,8))\n",
    "fviz_pca_ind(pca_fit_2020, \n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_20$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "fviz_pca_ind(pca_fit_2020, \n",
    "             axes=c(3,4),\n",
    "             geom.ind = 'point',\n",
    "             col.ind = data_20$league,\n",
    "             addEllipses = TRUE,\n",
    "             legend.title= \"Leagues\")\n",
    "\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=1, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=2, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=3, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=4, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=5, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=6, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=7, top=10)\n",
    "fviz_contrib(pca_fit_2020, choice = \"var\", axes=8, top=10)\n",
    "\n",
    "\n",
    "ggarrange(scree_pca_17, scree_pca_18, scree_pca_19, scree_pca_20,\n",
    "          ncol=2, nrow = 2, hjust = 0.5)\n",
    "#### HIERARCHICAL CLUSTERING ####\n",
    "# 2017 :\n",
    "# 8 PC's (+-75% of var. explained)\n",
    "dist_17_8PC <- dist(reduced_17[,-9], method = \"euclidean\")\n",
    "\n",
    "# Perform hier. clustering using 4 different critiria:\n",
    "hclust_17_compl_8PC <- hclust(d = dist_17_8PC, method = \"complete\")\n",
    "hclust_17_single_8PC <- hclust(d = dist_17_8PC, method = \"single\")\n",
    "hclust_17_avg_8PC <- hclust(d = dist_17_8PC, method = \"average\")\n",
    "hclust_17_ward_8PC <- hclust(d = dist_17_8PC, method = \"ward.D\")\n",
    "\n",
    "\n",
    "# Dendograms\n",
    "par(mfrow=c(2,2))\n",
    "plot(hclust_17_compl_8PC,main='Complete Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_17_single_8PC,main='Single Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_17_avg_8PC,main='Average Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_17_ward_8PC,main='Ward Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "par(mfrow=c(1,1))\n",
    "\n",
    "#color labels\n",
    "factor_leagues_2017 <- as.factor(reduced_17$leagues)\n",
    "colors_leagues_2017 <- as.numeric(factor_leagues_2017)\n",
    "hclust_17_ward_8PC <- as.dendrogram(hclust_17_ward_8PC)\n",
    "colors_leagues_2017 <- colors_leagues_2017[order.dendrogram(hclust_17_ward_8PC)]\n",
    "labels_colors(hclust_17_ward_8PC) <- colors_leagues_2017\n",
    "labels_leagues_2017 <- as.character(factor_leagues_2017)\n",
    "labels(hclust_17_ward_8PC) <- labels_leagues_2017[order.dendrogram(hclust_17_ward_8PC)]\n",
    "hclust_17_ward_8PC <- color_branches(hclust_17_ward_8PC, k = 4, col = c(3, 2, 7, 4))\n",
    "plot(hclust_17_ward_8PC, main=\"Dendogram for 2017 (Ward's Method)\")\n",
    "\n",
    "# 2018:\n",
    "# 8 PC's (+-75% of var. explained)\n",
    "dist_18_8PC <- dist(reduced_18[,-9], method = \"euclidean\")\n",
    "\n",
    "# Perform hier. clustering using 4 different critiria:\n",
    "hclust_18_compl_8PC <- hclust(d = dist_18_8PC, method = \"complete\")\n",
    "hclust_18_single_8PC <- hclust(d = dist_18_8PC, method = \"single\")\n",
    "hclust_18_avg_8PC <- hclust(d = dist_18_8PC, method = \"average\")\n",
    "hclust_18_ward_8PC <- hclust(d = dist_18_8PC, method = \"ward.D\")\n",
    "\n",
    "\n",
    "# Dendograms\n",
    "# Dendograms\n",
    "par(mfrow=c(2,2))\n",
    "plot(hclust_18_compl_8PC,main='Complete Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_18_single_8PC,main='Single Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_18_avg_8PC,main='Average Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_18_ward_8PC,main='Ward Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "par(mfrow=c(1,1))\n",
    "\n",
    "#color labels\n",
    "factor_leagues_2018 <- as.factor(data_18$league)\n",
    "colors_leagues_2018 <- as.numeric(factor_leagues_2018)\n",
    "hclust_18_ward_8PC <- as.dendrogram(hclust_18_ward_8PC)\n",
    "colors_leagues_2018 <- colors_leagues_2018[order.dendrogram(hclust_18_ward_8PC)]\n",
    "labels_colors(hclust_18_ward_8PC) <- colors_leagues_2018\n",
    "labels_leagues_2018 <- as.character(factor_leagues_2018)\n",
    "labels(hclust_18_ward_8PC) <- labels_leagues_2018[order.dendrogram(hclust_18_ward_8PC)]\n",
    "hclust_18_ward_8PC <- color_branches(hclust_18_ward_8PC, k = 5, col = c(3, 2, 7, 4, 6))\n",
    "plot(hclust_18_ward_8PC, main=\"Dendogram for 2018 (Ward's Method)\")\n",
    "\n",
    "# 2019:\n",
    "# 8 PC's (+-75% of var. explained)\n",
    "dist_19_8PC <- dist(reduced_19[,-9], method = \"euclidean\")\n",
    "\n",
    "# Perform hier. clustering using 4 different critiria:\n",
    "hclust_19_compl_8PC <- hclust(d = dist_19_8PC, method = \"complete\")\n",
    "hclust_19_single_8PC <- hclust(d = dist_19_8PC, method = \"single\")\n",
    "hclust_19_avg_8PC <- hclust(d = dist_19_8PC, method = \"average\")\n",
    "hclust_19_ward_8PC <- hclust(d = dist_19_8PC, method = \"ward.D\")\n",
    "\n",
    "\n",
    "# Dendograms\n",
    "# Dendograms\n",
    "par(mfrow=c(2,2))\n",
    "plot(hclust_19_compl_8PC,main='Complete Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_19_single_8PC,main='Single Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_19_avg_8PC,main='Average Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_19_ward_8PC,main='Ward Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "par(mfrow=c(1,1))\n",
    "\n",
    "#color labels\n",
    "factor_leagues_2019 <- as.factor(data_19$league)\n",
    "colors_leagues_2019 <- as.numeric(factor_leagues_2019)\n",
    "hclust_19_ward_8PC <- as.dendrogram(hclust_19_ward_8PC)\n",
    "colors_leagues_2019 <- colors_leagues_2019[order.dendrogram(hclust_19_ward_8PC)]\n",
    "labels_colors(hclust_19_ward_8PC) <- colors_leagues_2019\n",
    "labels_leagues_2019 <- as.character(factor_leagues_2019)\n",
    "labels(hclust_19_ward_8PC) <- labels_leagues_2019[order.dendrogram(hclust_19_ward_8PC)]\n",
    "hclust_19_ward_8PC <- color_branches(hclust_19_ward_8PC, k = 5, col = c(3, 2, 7, 4, 6))\n",
    "plot(hclust_19_ward_8PC, main=\"Dendogram for 2019 (Ward's Method)\")\n",
    "\n",
    "# 2020:\n",
    "# 8 PC's (+-75% of var. explained)\n",
    "dist_20_8PC <- dist(reduced_20[,-9], method = \"euclidean\")\n",
    "\n",
    "# Perform hier. clustering using 4 different critiria:\n",
    "hclust_20_compl_8PC <- hclust(d = dist_20_8PC, method = \"complete\")\n",
    "hclust_20_single_8PC <- hclust(d = dist_20_8PC, method = \"single\")\n",
    "hclust_20_avg_8PC <- hclust(d = dist_20_8PC, method = \"average\")\n",
    "hclust_20_ward_8PC <- hclust(d = dist_20_8PC, method = \"ward.D\")\n",
    "\n",
    "\n",
    "# Dendograms\n",
    "# Dendograms\n",
    "par(mfrow=c(2,2))\n",
    "plot(hclust_20_compl_8PC,main='Complete Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_20_single_8PC,main='Single Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_20_avg_8PC,main='Average Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "plot(hclust_20_ward_8PC,main='Ward Linkage', \n",
    "     labels=FALSE, hang = -1, xlab = \"\", sub=\"\")\n",
    "par(mfrow=c(1,1))\n",
    "\n",
    "#color labels\n",
    "factor_leagues_2020 <- as.factor(data_20$league)\n",
    "colors_leagues_2020 <- as.numeric(factor_leagues_2020)\n",
    "hclust_20_ward_8PC <- as.dendrogram(hclust_20_ward_8PC)\n",
    "colors_leagues_2020 <- colors_leagues_2020[order.dendrogram(hclust_20_ward_8PC)]\n",
    "labels_colors(hclust_20_ward_8PC) <- colors_leagues_2020\n",
    "labels_leagues_2020 <- as.character(factor_leagues_2020)\n",
    "labels(hclust_20_ward_8PC) <- labels_leagues_2020[order.dendrogram(hclust_20_ward_8PC)]\n",
    "hclust_20_ward_8PC <- color_branches(hclust_20_ward_8PC, k = 4, col = c(3, 2, 7, 4))\n",
    "plot(hclust_20_ward_8PC, main=\"Dendogram for 2020 (Ward's Method)\")\n",
    "\n",
    "#### K-MEANS CLUSTERING ####\n",
    "\n",
    "## 2017: ##\n",
    "# elbow method for K using within SS\n",
    "wss_k_17 <- fviz_nbclust(reduced_17[,-9], kmeans, method = \"wss\") +\n",
    "  geom_vline(xintercept = 4, linetype = 2)+\n",
    "  labs(title=\"2017\")\n",
    "wss_k_17\n",
    "# proposes 4\n",
    "\n",
    "### As hierarchical Clustering, and the elbow optimalisation methods proposes\n",
    "### 4 clusters as optimal number of clusters:\n",
    "km_fit_2017 <- kmeans(x = reduced_17[,-9],  # use reduced data set\n",
    "                      centers = 4,     # K = 4 for 2017\n",
    "                      iter.max = 2000, # maximum iterations of the algorithm\n",
    "                      nstart = 100)    # randomly use 100 centers\n",
    "km_fit_2017$centers\n",
    "df_km_centers_17 <- as.data.frame(km_fit_2017$centers)\n",
    "rownames(df_km_centers_17) <- paste(\"Cluster\" , c(1:4), sep=\" \")\n",
    "\n",
    "# # radarchart source: https://www.r-graph-gallery.com/143-spider-chart-with-saveral-individuals.html\n",
    "# colors_in    =c(rgb(0.2,0.5,0.5,0.3), \n",
    "#                 rgb(0.8,0.2,0.5,0.3), \n",
    "#                 rgb(0.7,0.5,0.1,0.3),\n",
    "#                 rgb(0.5,0.8,0.1,0.3))\n",
    "# colors_border=c(rgb(0.2,0.5,0.5,0.9), \n",
    "#                 rgb(0.8,0.2,0.5,0.9), \n",
    "#                 rgb(0.7,0.5,0.1,0.9),\n",
    "#                 rgb(0.5,0.8,0.1,0.9))\n",
    "# radarchart(df_km_centers_17, \n",
    "#            maxmin = FALSE, plwd=2 , plty=1,\n",
    "#            pfcol = colors_in, pcol=colors_border,\n",
    "#            cglcol=\"grey\", cglty=1, \n",
    "#            axislabcol=\"grey\", caxislabels=seq(0,20,5), \n",
    "#            cglwd=0.8, vlcex=0.8)\n",
    "# # Add a legend\n",
    "# legend(x=1.2, y=1.2, \n",
    "#        legend = rownames(df_km_centers_17), \n",
    "#        bty = \"n\", pch=20 , \n",
    "#        col=colors_in , text.col = \"darkgrey\", \n",
    "#        cex=1.3, pt.cex=3)\n",
    "\n",
    "# barplot per cluster:\n",
    "cl_df_2017_barplot <- df_km_centers_17 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"cluster\", value=value, -1)\n",
    "\n",
    "# View(df_2017_barplot)\n",
    "\n",
    "cl_df_2017_barplot %>% ggplot( aes(x=rowname, y=value, fill=cluster)) +\n",
    "        geom_bar(stat=\"identity\",  width=0.4) +\n",
    "        coord_flip() +\n",
    "        theme_bw() +\n",
    "        theme(\n",
    "          panel.grid.minor.y = element_blank(),\n",
    "          panel.grid.major.y = element_blank(),\n",
    "          axis.text = element_text(size=12),\n",
    "          legend.position = \"none\",\n",
    "          plot.title = element_text(hjust = 0.5)\n",
    "        ) +\n",
    "        ylim(min(df_km_centers_17), max(df_km_centers_17)) +\n",
    "        ylab(\"Cluster mean per PC\") +\n",
    "        xlab(\"\") +\n",
    "        facet_wrap(~cluster, ncol=2) +\n",
    "        ggtitle(\"K-means cluster results 2017\")\n",
    "\n",
    "data_17$cluster <- as.factor(km_fit_2017$cluster)\n",
    "cross_tab_17 <- descr::CrossTable(data_17$league, \n",
    "                                  data_17$cluster,\n",
    "                                  prop.chisq = F,\n",
    "                                  row.labels = T,\n",
    "                                  prop.t=F)\n",
    "print(xtable(cross_tab_17, digits=2), include.rownames=FALSE)\n",
    "\n",
    "\n",
    "## 2018: ##\n",
    "# Get dendogram once more:\n",
    "plot(hclust_18_ward_8PC)\n",
    "# One could make valid arguments for 3, 4 or 5 as k --> optimalisation\n",
    "# elbow method for K\n",
    "wss_k_18 <- fviz_nbclust(reduced_18[,-9], kmeans, method = \"wss\") +\n",
    "  geom_vline(xintercept = 4, linetype = 2)+\n",
    "  labs(title=\"2018\")\n",
    "wss_k_18\n",
    "# proposes 4\n",
    "\n",
    "### As hierarchical Clustering, and the elbow optimalisation methods proposes\n",
    "### 4 clusters as optimal number of clusters:\n",
    "km_fit_2018 <- kmeans(x = reduced_18[,-9], # use reduced data set\n",
    "                      centers = 4,    # K = 4 for 2018\n",
    "                      iter.max = 2000, # maximum iterations of the algorithm\n",
    "                      nstart = 100)    # randomly use 100 centers\n",
    "km_fit_2018$centers\n",
    "df_km_centers_18 <- as.data.frame(km_fit_2018$centers)\n",
    "rownames(df_km_centers_18) <- paste(\"Cluster\" , c(1:4), sep=\" \")\n",
    "\n",
    "# # radarchart source: https://www.r-graph-gallery.com/143-spider-chart-with-saveral-individuals.html\n",
    "# radarchart(df_km_centers_18, \n",
    "#            maxmin = FALSE, plwd=2 , plty=1,\n",
    "#            pfcol = colors_in, pcol=colors_border,\n",
    "#            cglcol=\"grey\", cglty=1, \n",
    "#            axislabcol=\"grey\", caxislabels=seq(0,20,5), \n",
    "#            cglwd=0.8, vlcex=0.8)\n",
    "# # Add a legend\n",
    "# legend(x=1.2, y=1.2, \n",
    "#        legend = rownames(df_km_centers_18), \n",
    "#        bty = \"n\", pch=20 , \n",
    "#        col=colors_in , text.col = \"darkgrey\", \n",
    "#        cex=1.3, pt.cex=3)\n",
    "\n",
    "# barplot per cluster:\n",
    "cl_df_2018_barplot <- df_km_centers_18 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"cluster\", value=value, -1)\n",
    "\n",
    "# View(df_2018_barplot)\n",
    "\n",
    "cl_df_2018_barplot %>% ggplot( aes(x=rowname, y=value, fill=cluster)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(-max(df_km_centers_18), max(df_km_centers_18)) +\n",
    "  ylab(\"Cluster mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~cluster, ncol=2) +\n",
    "  ggtitle(\"K-means cluster results for 2018\")\n",
    "\n",
    "data_18$cluster <- as.factor(km_fit_2018$cluster)\n",
    "\n",
    "cross_tab_18 <- descr::CrossTable(data_18$league, \n",
    "                                  data_18$cluster,\n",
    "                                  prop.chisq = F,\n",
    "                                  row.labels = T,\n",
    "                                  prop.t=F)\n",
    "print(xtable(cross_tab_18, digits=2), include.rownames=FALSE)\n",
    "\n",
    "## 2019 ##\n",
    "# plot dendogram again:\n",
    "plot(hclust_19_ward_8PC, main=\"2019 dendogram\")\n",
    "\n",
    "# One could make valid arguments for 3, 4 or 5 as k --> optimalisation\n",
    "# elbow method for K\n",
    "wss_k_19 <- fviz_nbclust(reduced_19[,-9], kmeans, method = \"wss\") +\n",
    "  geom_vline(xintercept = 4, linetype = 2)+\n",
    "  labs(title=\"2019\")\n",
    "wss_k_19\n",
    "# proposes 4\n",
    "\n",
    "### As hierarchical Clustering, and the elbow optimalisation methods proposes\n",
    "### 4 clusters as optimal number of clusters:\n",
    "km_fit_2019 <- kmeans(x = reduced_19[,-9], # use reduced data set\n",
    "                      centers = 4,    # K = 4 for 2018\n",
    "                      iter.max = 2000, # maximum iterations of the algorithm\n",
    "                      nstart = 100)    # randomly use 100 centers\n",
    "km_fit_2019$centers\n",
    "df_km_centers_19 <- as.data.frame(km_fit_2019$centers)\n",
    "rownames(df_km_centers_19) <- paste(\"Cluster\" , c(1:4), sep=\" \")\n",
    "\n",
    "# # radarchart source: https://www.r-graph-gallery.com/143-spider-chart-with-saveral-individuals.html\n",
    "# radarchart(df_km_centers_19, \n",
    "#            maxmin = FALSE, plwd=2 , plty=1,\n",
    "#            pfcol = colors_in, pcol=colors_border,\n",
    "#            cglcol=\"grey\", cglty=1, \n",
    "#            axislabcol=\"grey\", caxislabels=seq(0,20,5), \n",
    "#            cglwd=0.8, vlcex=0.8)\n",
    "# # Add a legend\n",
    "# legend(x=1.2, y=1.2, \n",
    "#        legend = rownames(df_km_centers_19), \n",
    "#        bty = \"n\", pch=20 , \n",
    "#        col=colors_in , text.col = \"darkgrey\", \n",
    "#        cex=1.3, pt.cex=3)\n",
    "\n",
    "# barplot per cluster:\n",
    "cl_df_2019_barplot <- df_km_centers_19 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"cluster\", value=value, -1)\n",
    "\n",
    "# View(df_2019_barplot)\n",
    "\n",
    "cl_df_2019_barplot %>% ggplot( aes(x=rowname, y=value, fill=cluster)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(df_km_centers_19), max(df_km_centers_19)) +\n",
    "  ylab(\"Cluster mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~cluster, ncol=2) +\n",
    "  ggtitle(\"K-means cluster results for 2019\")\n",
    "\n",
    "data_19$cluster <- as.factor(km_fit_2019$cluster)\n",
    "\n",
    "cross_tab_19 <- descr::CrossTable(data_19$league, \n",
    "                                  data_19$cluster,\n",
    "                                  prop.chisq = F,\n",
    "                                  row.labels = T,\n",
    "                                  prop.t=F)\n",
    "print(xtable(cross_tab_19, digits=2), include.rownames=FALSE)\n",
    "\n",
    "\n",
    "## 2020: ##\n",
    "# plot dendogram again:\n",
    "plot(hclust_20_ward_8PC, main=\"2020 dendogram\")\n",
    "\n",
    "# One could make valid arguments for 3, 4 or 5 as k --> optimalisation\n",
    "# elbow method for K\n",
    "wss_k_20 <- fviz_nbclust(reduced_20[,-9], kmeans, method = \"wss\") +\n",
    "  geom_vline(xintercept = 4, linetype = 2)+\n",
    "  labs(title=\"2020\")\n",
    "wss_k_20\n",
    "# proposes 4\n",
    "\n",
    "### As hierarchical Clustering, and the elbow optimalisation methods proposes\n",
    "### 4 clusters as optimal number of clusters:\n",
    "km_fit_2020 <- kmeans(x = reduced_20[,-9], # use reduced data set\n",
    "                      centers = 4,    # K = 4 for 2018\n",
    "                      iter.max = 2000, # maximum iterations of the algorithm\n",
    "                      nstart = 100)    # randomly use 100 centers\n",
    "km_fit_2020$centers\n",
    "df_km_centers_20 <- as.data.frame(km_fit_2020$centers)\n",
    "rownames(df_km_centers_20) <- paste(\"Cluster\" , c(1:4), sep=\" \")\n",
    "\n",
    "# # radarchart source: https://www.r-graph-gallery.com/143-spider-chart-with-saveral-individuals.html\n",
    "# radarchart(df_km_centers_20, \n",
    "#            maxmin = FALSE, plwd=2 , plty=1,\n",
    "#            pfcol = colors_in, pcol=colors_border,\n",
    "#            cglcol=\"grey\", cglty=1, \n",
    "#            axislabcol=\"grey\", caxislabels=seq(0,20,5), \n",
    "#            cglwd=0.8, vlcex=0.8)\n",
    "# # Add a legend\n",
    "# legend(x=1.2, y=1.2, \n",
    "#        legend = rownames(df_km_centers_20), \n",
    "#        bty = \"n\", pch=20 , \n",
    "#        col=colors_in , text.col = \"darkgrey\", \n",
    "#        cex=1.3, pt.cex=3)\n",
    "\n",
    "# barplot per cluster:\n",
    "cl_df_2020_barplot <- df_km_centers_20 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"cluster\", value=value, -1)\n",
    "\n",
    "# View(df_2020_barplot)\n",
    "\n",
    "cl_df_2020_barplot %>% ggplot( aes(x=rowname, y=value, fill=cluster)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(df_km_centers_20), max(df_km_centers_20)) +\n",
    "  ylab(\"Cluster mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~cluster, ncol=2) +\n",
    "  ggtitle(\"K-means cluster results for 2020\")\n",
    "\n",
    "data_20$cluster <- as.factor(km_fit_2020$cluster)\n",
    "\n",
    "cross_tab_20 <- descr::CrossTable(data_20$league, \n",
    "                                  data_20$cluster,\n",
    "                                  prop.chisq = F,\n",
    "                                  row.labels = T,\n",
    "                                  prop.t=F)\n",
    "print(xtable(cross_tab_20, digits=2), include.rownames=FALSE)\n",
    "\n",
    "# df_reduced_20 <- reduced_20 %>%\n",
    "#   as.data.frame() %>%\n",
    "#   mutate(cluster = as.factor(km_fit_2020$cluster))\n",
    "# str(df_reduced_20)\n",
    "# ggplot(data=df_reduced_20, aes(PC1, PC2, color=cluster, shape=data_20$league))+\n",
    "#   geom_point()\n",
    "\n",
    "# all WSS plots in 1 graphic:\n",
    "ggarrange(wss_k_17, wss_k_18, wss_k_19, wss_k_20)\n",
    "\n",
    "\n",
    "\n",
    "#### DISCRIMINANT ANALYSES ####\n",
    "\n",
    "## DO RUN:\n",
    "\n",
    "# function for deciding how many subclasses to use for MDA (based on accuracy):\n",
    "mda_subclasses <- function(data_mod, data_ref, nsub = 4, nleag = 5) {\n",
    "  accuracies <- rep(0, nleag**nsub)\n",
    "  \n",
    "  # initialize permutations\n",
    "  # source: https://www.r-bloggers.com/2019/06/learning-r-permutations-and-combinations-with-base-r/\n",
    "  perm <- expand.grid(rep(list(1:nsub), nleag))\n",
    "  \n",
    "  for (i in c(1:nrow(perm))) {\n",
    "    fit <- mda(leagues~., data=data_mod, subclasses = as.numeric(as.vector(perm[i,])))\n",
    "    pred <- predict(fit, data_mod)\n",
    "    conf_mat <- confusionMatrix(pred, data_ref$league)\n",
    "    \n",
    "    accuracies[i] <- conf_mat$overall[1]\n",
    "  }\n",
    "  \n",
    "  best <- max(accuracies)\n",
    "  best_index <- match(best, accuracies)\n",
    "  best_fit <- as.numeric(as.vector(perm[best_index,]))\n",
    "  print(paste(\"The best model has an accuracy of\", best, \n",
    "              \"(using c(\", toString(as.character(as.vector(perm[best_index,]))), \") subclasses)\"))\n",
    "  best_output <- mda(leagues~., data=data_mod, subclasses = best_fit)\n",
    "}\n",
    "\n",
    "\n",
    "# mda_fit_17 <- mda_subclasses(reduced_17, data_17, nleag = 6)\n",
    "# mda_fit_18 <- mda_subclasses(reduced_18, data_18)\n",
    "# mda_fit_19 <- mda_subclasses(reduced_19, data_19)\n",
    "# mda_fit_20 <- mda_subclasses(reduced_20, data_20)\n",
    "\n",
    "mda_fit_17 <- readRDS(\"mda_fit_17.rds\")\n",
    "mda_fit_18 <- readRDS(\"mda_fit_18.rds\")\n",
    "mda_fit_19 <- readRDS(\"mda_fit_19.rds\")\n",
    "mda_fit_20 <- readRDS(\"mda_fit_20.rds\")\n",
    "\n",
    "# fit MDA and check accuracy\n",
    "mda_pred_17 <- predict(mda_fit_17, reduced_17)\n",
    "mda_fit_17\n",
    "\n",
    "cm_mda_17 <- confusionMatrix(mda_pred_17, data_17$league)\n",
    "cm_mda_17\n",
    "\n",
    "mda_pred_18 <- predict(mda_fit_18, reduced_18)\n",
    "mda_fit_18\n",
    "\n",
    "cm_mda_18 <- confusionMatrix(mda_pred_18, data_18$league)\n",
    "cm_mda_18\n",
    "\n",
    "mda_pred_19 <- predict(mda_fit_19, reduced_19)\n",
    "mda_fit_19\n",
    "\n",
    "cm_mda_19 <- confusionMatrix(mda_pred_19, data_19$league)\n",
    "cm_mda_19\n",
    "\n",
    "mda_pred_20 <- predict(mda_fit_20, reduced_20)\n",
    "mda_fit_20\n",
    "\n",
    "cm_mda_20 <- confusionMatrix(mda_pred_20, data_20$league)\n",
    "cm_mda_20\n",
    "\n",
    "###### DISC. ANAL. DONE ####\n",
    "\n",
    "## 2017:\n",
    "# fit LDA\n",
    "lda_fit_17 <- lda(leagues~., data=reduced_17)\n",
    "lda_pred_17 <- predict(lda_fit_17, reduced_17)\n",
    "lda_fit_17\n",
    "# Check accuracy:\n",
    "cm_lda_17 <- confusionMatrix(lda_pred_17$class, data_17$league)\n",
    "cm_lda_17\n",
    "\n",
    "# fit QDA and check accuracy\n",
    "qda_fit_17 <- qda(leagues~., data=reduced_17)\n",
    "qda_pred_17 <- predict(qda_fit_17, reduced_17)\n",
    "qda_fit_17\n",
    "\n",
    "cm_qda_17 <- confusionMatrix(qda_pred_17$class, data_17$league)\n",
    "cm_qda_17\n",
    "\n",
    "# fit MDA and check accuracy\n",
    "mda_pred_17 <- predict(mda_fit_17, reduced_17)\n",
    "mda_fit_17\n",
    "\n",
    "cm_mda_17 <- confusionMatrix(mda_pred_17, data_17$league)\n",
    "cm_mda_17\n",
    "\n",
    "# barplot per league for lda results:\n",
    "lda_df_2017_barplot <- lda_fit_17$means %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"league\", value=value, -1)\n",
    "\n",
    "lda_df_2017_barplot %>% ggplot( aes(x=rowname, y=value, fill=league)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(lda_fit_17$means), -min(lda_fit_17$means)) +\n",
    "  ylab(\"League mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~league, ncol=3) +\n",
    "  ggtitle(\"Mean score on PC's per league (2017):\")\n",
    "\n",
    "lda_post_df_17 <- cbind(reduced_17, lda_pred_17$x)\n",
    "\n",
    "ggplot(lda_post_df_17, aes(LD1, LD2)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "ggplot(lda_post_df_17, aes(LD3, LD4)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "ggplot(lda_post_df_17, aes(LD1, LD5)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "\n",
    "\n",
    "## 2018:\n",
    "# fit LDA\n",
    "lda_fit_18 <- lda(leagues~., data=reduced_18)\n",
    "lda_pred_18 <- predict(lda_fit_18, reduced_18)\n",
    "lda_fit_18\n",
    "# Check accuracy:\n",
    "cm_lda_18 <- confusionMatrix(lda_pred_18$class, data_18$league)\n",
    "cm_lda_18\n",
    "\n",
    "# fit QDA and check accurary\n",
    "qda_fit_18 <- qda(leagues~., data=reduced_18)\n",
    "qda_pred_18 <- predict(qda_fit_18, reduced_18)\n",
    "qda_fit_18\n",
    "\n",
    "cm_qda_18 <- confusionMatrix(qda_pred_18$class, data_18$league)\n",
    "cm_qda_18\n",
    "\n",
    "# fit MDA and check accurary\n",
    "mda_pred_18 <- predict(mda_fit_18, reduced_18)\n",
    "mda_fit_18\n",
    "\n",
    "cm_mda_18 <- confusionMatrix(mda_pred_18, data_18$league)\n",
    "cm_mda_18\n",
    "\n",
    "# barplot per league for lda results:\n",
    "lda_df_2018_barplot <- lda_fit_18$means %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"league\", value=value, -1)\n",
    "\n",
    "lda_df_2018_barplot %>% ggplot( aes(x=rowname, y=value, fill=league)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(-max(lda_fit_18$means), max(lda_fit_18$means)) +\n",
    "  ylab(\"League mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~league, ncol=2) +\n",
    "  ggtitle(\"Mean score on PC's per league (2018):\")\n",
    "\n",
    "lda_post_df_18 <- cbind(reduced_18, lda_pred_18$x)\n",
    "\n",
    "ggplot(lda_post_df_18, aes(LD1, LD2)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "ggplot(lda_post_df_18, aes(LD3, LD4)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "\n",
    "## 2019:\n",
    "# fit LDA\n",
    "lda_fit_19 <- lda(leagues~., data=reduced_19)\n",
    "lda_pred_19 <- predict(lda_fit_19, reduced_19)\n",
    "lda_fit_19\n",
    "# Check accuracy:\n",
    "cm_lda_19 <- confusionMatrix(lda_pred_19$class, data_19$league)\n",
    "cm_lda_19\n",
    "\n",
    "# fit QDA and check accurary\n",
    "qda_fit_19 <- qda(leagues~., data=reduced_19)\n",
    "qda_pred_19 <- predict(qda_fit_19, reduced_19)\n",
    "qda_fit_19\n",
    "\n",
    "cm_qda_19 <- confusionMatrix(qda_pred_19$class, data_19$league)\n",
    "cm_qda_19\n",
    "\n",
    "# fit MDA and check accurary\n",
    "mda_pred_19 <- predict(mda_fit_19, reduced_19)\n",
    "mda_fit_19\n",
    "\n",
    "cm_mda_19 <- confusionMatrix(mda_pred_19, data_19$league)\n",
    "cm_mda_19\n",
    "\n",
    "# barplot per league for lda results:\n",
    "lda_df_2019_barplot <- lda_fit_19$means %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"league\", value=value, -1)\n",
    "\n",
    "lda_df_2019_barplot %>% ggplot( aes(x=rowname, y=value, fill=league)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(-max(lda_fit_19$means), max(lda_fit_19$means)) +\n",
    "  ylab(\"League mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~league, ncol=2) +\n",
    "  ggtitle(\"Mean score on PC's per league (2019):\")\n",
    "\n",
    "lda_post_df_19 <- cbind(reduced_19, lda_pred_19$x)\n",
    "\n",
    "ggplot(lda_post_df_19, aes(LD1, LD2)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "ggplot(lda_post_df_19, aes(LD3, LD4)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "\n",
    "\n",
    "## 2020:\n",
    "# fit LDA\n",
    "lda_fit_20 <- lda(leagues~., data=reduced_20)\n",
    "lda_pred_20 <- predict(lda_fit_20, reduced_20)\n",
    "lda_fit_20\n",
    "# Check accuracy:\n",
    "cm_lda_20 <- confusionMatrix(lda_pred_20$class, data_20$league)\n",
    "cm_lda_20\n",
    "\n",
    "# fit QDA and check accurary\n",
    "qda_fit_20 <- qda(leagues~., data=reduced_20)\n",
    "qda_pred_20 <- predict(qda_fit_20, reduced_20)\n",
    "qda_fit_20\n",
    "\n",
    "cm_qda_20 <- confusionMatrix(qda_pred_20$class, data_20$league)\n",
    "cm_qda_20\n",
    "\n",
    "# fit MDA and check accurary\n",
    "mda_pred_20 <- predict(mda_fit_20, reduced_20)\n",
    "mda_fit_20\n",
    "\n",
    "cm_mda_20 <- confusionMatrix(mda_pred_20, data_20$league)\n",
    "cm_mda_20\n",
    "# barplot per league for lda results:\n",
    "lda_df_2020_barplot <- lda_fit_20$means %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"league\", value=value, -1)\n",
    "\n",
    "lda_df_2020_barplot %>% ggplot( aes(x=rowname, y=value, fill=league)) +\n",
    "  geom_bar(stat=\"identity\", width=0.5) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text( size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(-max(lda_fit_20$means), max(lda_fit_20$means)) +\n",
    "  ylab(\"League mean per PC\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~league, ncol=2) +\n",
    "  ggtitle(\"Mean score on PC's per league (2020):\")\n",
    "\n",
    "lda_post_df_20 <- cbind(reduced_20, lda_pred_20$x)\n",
    "\n",
    "ggplot(lda_post_df_20, aes(LD1, LD2)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "ggplot(lda_post_df_20, aes(LD3, LD4)) +\n",
    "  geom_point(aes(color = leagues))\n",
    "\n",
    "\n",
    "#### RESULTS ####\n",
    "\n",
    "coef_17 <- mda_fit_17$fit$coefficients[2:9,1:5]\n",
    "coef_18 <- mda_fit_18$fit$coefficients[2:9,1:5]\n",
    "coef_19 <- mda_fit_19$fit$coefficients[2:9,1:4]\n",
    "coef_20 <- mda_fit_20$fit$coefficients[2:9,1:5]\n",
    "colnames_DA <- paste(\"Function\" , c(1:5), sep=\" \")\n",
    "colnames(coef_17) <- colnames_DA\n",
    "colnames(coef_18) <- colnames_DA\n",
    "colnames(coef_19) <- colnames_DA[1:4]\n",
    "colnames(coef_20) <- colnames_DA\n",
    "\n",
    "## 2017:\n",
    "# barplot per cluster:\n",
    "coef_2017_barplot <- coef_17 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"PC\", value=value, -1)\n",
    "\n",
    "# View(df_2017_barplot)\n",
    "\n",
    "coef_2017_barplot %>% ggplot( aes(x=PC, y=value, fill=rowname)) +\n",
    "  geom_bar(stat=\"identity\",  width=0.4) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text(size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(coef_2017_barplot$value), max(coef_2017_barplot$value)) +\n",
    "  ylab(\"Coefficients of discriminant functions\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~rowname, ncol=2) +\n",
    "  ggtitle(\"Coefficients of discriminant functions for 2017\")\n",
    "\n",
    "\n",
    "# VISUALIZE by scatterplot:\n",
    "# df_means_mda_17 <- as.data.frame(mda_fit_17$means)\n",
    "# df_means_mda_17 <- tibble::rownames_to_column(df_means_mda_17, \"Region\")\n",
    "# \n",
    "# cols_mda <- factor(x = c(rep(1, 3), rep(2, 3), rep(3,4), 4,4,5,5,5,6,6,6,6), \n",
    "#                    labels = c(\"EU LCS\", \"GPL\", \"LCK\", \"LMS\", \"NA LCS\", \"TCL\"))\n",
    "# \n",
    "# ggplot(df_means_mda_17, \n",
    "#        aes(x = v1, y = v2, \n",
    "#            col=cols_mda)) + geom_point() +\n",
    "#   theme_bw()+\n",
    "#   geom_text(aes(label=Region),hjust=0.5, vjust=-0.5)\n",
    "\n",
    "## 2018:\n",
    "# barplot per cluster:\n",
    "coef_2018_barplot <- coef_18 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"PC\", value=value, -1)\n",
    "\n",
    "# View(df_2018_barplot)\n",
    "\n",
    "coef_2018_barplot %>% ggplot( aes(x=PC, y=value, fill=rowname)) +\n",
    "  geom_bar(stat=\"identity\",  width=0.4) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text(size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(-max(coef_2018_barplot$value), max(coef_2018_barplot$value)) +\n",
    "  ylab(\"Coefficients of discriminant functions\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~rowname, ncol=2) +\n",
    "  ggtitle(\"Coefficients of discriminant functions for 2018\")\n",
    "\n",
    "\n",
    "## 2019:\n",
    "# barplot per cluster:\n",
    "coef_2019_barplot <- coef_19 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"PC\", value=value, -1)\n",
    "\n",
    "# View(df_2019_barplot)\n",
    "\n",
    "coef_2019_barplot %>% ggplot( aes(x=PC, y=value, fill=rowname)) +\n",
    "  geom_bar(stat=\"identity\",  width=0.4) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text(size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(coef_2019_barplot$value), -min(coef_2019_barplot$value)) +\n",
    "  ylab(\"Coefficients of discriminant functions\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~rowname, ncol=2) +\n",
    "  ggtitle(\"Coefficients of discriminant functions for 2019\")\n",
    "\n",
    "\n",
    "## 2020:\n",
    "# barplot per cluster:\n",
    "coef_2020_barplot <- coef_20 %>% \n",
    "  t() %>% \n",
    "  as.data.frame() %>% \n",
    "  add_rownames() %>% \n",
    "  arrange() %>% \n",
    "  mutate(rowname=factor(rowname, rowname)) %>% \n",
    "  gather(key=\"PC\", value=value, -1)\n",
    "\n",
    "# View(df_2020_barplot)\n",
    "\n",
    "coef_2020_barplot %>% ggplot( aes(x=PC, y=value, fill=rowname)) +\n",
    "  geom_bar(stat=\"identity\",  width=0.4) +\n",
    "  coord_flip() +\n",
    "  theme_bw() +\n",
    "  theme(\n",
    "    panel.grid.minor.y = element_blank(),\n",
    "    panel.grid.major.y = element_blank(),\n",
    "    axis.text = element_text(size=12),\n",
    "    legend.position = \"none\",\n",
    "    plot.title = element_text(hjust = 0.5)\n",
    "  ) +\n",
    "  ylim(min(coef_2020_barplot$value), -min(coef_2020_barplot$value)) +\n",
    "  ylab(\"Coefficients of discriminant functions\") +\n",
    "  xlab(\"\") +\n",
    "  facet_wrap(~rowname, ncol=2) +\n",
    "  ggtitle(\"Coefficients of discriminant functions for 2020\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 12.40525,
   "end_time": "2023-04-16T19:39:49.790449",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2023-04-16T19:39:37.385199",
   "version": "2.4.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
